language: python
os: osx

matrix:
    fast_finish: true
    include:
        - language: python
          python: 3.6
          osx_image: xcode10


before_install:
    - brew install autoconf automake libtool pkg-config
    - brew link libtool
    - pip install Cython==0.26.1
    - git clone https://github.com/kivy/kivy

script:
    - ./toolchain.py build openssl kivy
    - ./toolchain.py create touchtracer $PWD/kivy/examples/touchtracer
